---
title: "Análise expoloratória dos discursos referente as sessões em Plenário da PEC 06/2019"
output: html_notebook
---

```{r, message=FALSE, include=FALSE, warning=FALSE}
library(tidyverse)
library(readr)
```

```{r, message=FALSE, warning=FALSE}
previdencia_06_08_19h <- read_csv("../data/process-data/previdencia_06-08-19h.csv")
previdencia_06_08_21h <- read_csv("../data/process-data/previdencia_06-08-21h.csv")
previdencia_07_08_17h <- read_csv("../data/process-data/previdencia_07-08-17h.csv")
previdencia_07_08_9h <- read_csv("../data/process-data/previdencia_07-08-9h.csv")
previdencia_09_07_16h <- read_csv("../data/process-data/previdencia_09-07-16h.csv")
previdencia_09_07_20h <- read_csv("../data/process-data/previdencia_09-07-20h.csv")
previdencia_10_07_16h <- read_csv("../data/process-data/previdencia_10-07-16h.csv")
previdencia_10_07_9h <- read_csv("../data/process-data/previdencia_10-07-9h.csv")
previdencia_11_07_9h <- read_csv("../data/process-data/previdencia_11-07-9h.csv")
previdencia_11_07_22h <- read_csv("../data/process-data/previdencia_11-07-22h.csv")
previdencia_12_07_16h <- read_csv("../data/process-data/previdencia_12-07-16h.csv")
previdencia_12_07_9h <- read_csv("../data/process-data/previdencia_12-07-9h.csv")

previdencia <- bind_rows(previdencia_06_08_19h,
                         previdencia_06_08_21h,
                         previdencia_07_08_9h,
                         previdencia_07_08_17h,
                         previdencia_09_07_16h,
                         previdencia_09_07_20h,
                         previdencia_10_07_9h,
                         previdencia_10_07_16h,
                         previdencia_11_07_9h,
                         previdencia_11_07_22h,
                         previdencia_12_07_9h,
                         previdencia_12_07_16h)

```

Questionamentos:

- Quais parlamentares falam mais/menos?(Contar quantas vezes eles aparecem e palavras em seus discursos)
- Quais partidos falam mais/menos?
- Quais são as palavras mais utilizadas? Se for possível gerar visu por partido e parlamentar.

```{r, message=FALSE, warning=FALSE}

```

```{r, message=FALSE, warning=FALSE}

```

```{r, message=FALSE, warning=FALSE}

```

```{r, message=FALSE, warning=FALSE}

```

```{r, message=FALSE, warning=FALSE}

```

```{r, message=FALSE, warning=FALSE}

```